# Generated by Django 5.0.14 on 2026-07-08 20:31

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('couple_name', models.CharField(blank=True, max_length=160)),
                ('event_type', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('corporate', 'Evenement professionnel'), ('other', 'Autre')], default='wedding', max_length=32)),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=events.models.event_cover_upload_path)),
                ('welcome_message', models.TextField(blank=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=events.models.event_qr_code_upload_path)),
                ('is_active', models.BooleanField(default=True)),
                ('media_retention_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
