# Generated by Django 5.0.14 on 2026-07-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_guest_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_provider',
            field=models.CharField(blank=True, default='manual', max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Paye'), ('failed', 'Echec'), ('refunded', 'Rembourse')], default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='event',
            name='price_amount',
            field=models.PositiveIntegerField(default=5900),
        ),
        migrations.AddField(
            model_name='event',
            name='price_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
