# Generated by Django 5.0.14 on 2026-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_paid_at_event_payment_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
