# Generated by Django 5.2.16 on 2026-07-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_accent_event_type_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('tagline', models.CharField(blank=True, help_text='Phrase courte affichee sous le nom de la formule.', max_length=160)),
                ('max_guests', models.PositiveIntegerField(default=0, help_text="Nombre d'invites annonce, pour l'affichage. 0 = sans limite affichee.")),
                ('upload_quota', models.PositiveIntegerField(default=0, help_text="Nombre de souvenirs (photos + videos) inclus. C'est la limite reellement appliquee. 0 = utiliser la limite globale du site.")),
                ('price_amount', models.PositiveIntegerField(default=0, help_text='Prix en centimes. Exemple : 7900 pour 79 USD. 0 = prix global du site.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Formule pre-selectionnee a la creation d'un evenement.")),
            ],
            options={
                'verbose_name': 'formule',
                'verbose_name_plural': 'formules',
                'ordering': ['sort_order', 'price_amount', 'label'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Formule choisie : fixe le prix et le quota de souvenirs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventplan'),
        ),
    ]
