# Generated by Django 5.2.16 on 2026-07-27 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_default_event_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Remise appliquee, en centimes.'),
        ),
        migrations.AddField(
            model_name='event',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taux de remise applique, fige a la creation.', max_digits=5),
        ),
        migrations.AddField(
            model_name='event',
            name='full_price_amount',
            field=models.PositiveIntegerField(default=0, help_text="Prix avant remise, en centimes. Egal au prix paye s'il n'y a pas de remise."),
        ),
        migrations.AddField(
            model_name='event',
            name='promo_code',
            field=models.CharField(blank=True, default='', help_text='Code ambassadeur utilise pour la remise de bienvenue.', max_length=12),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='max_guests',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'invités annoncé, pour l'affichage. 0 = sans limite affichée."),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='upload_quota',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de souvenirs (photos + vidéos) inclus. C'est la limite réellement appliquée. 0 = utiliser la limite globale du site."),
        ),
    ]
