# Generated by Django 5.2.16 on 2026-08-31 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_discount_amount_event_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guestbook_agent',
            field=models.ForeignKey(blank=True, help_text="Agent Memora affecte au livre d'or video de cet evenement. Affectation geree en interne.", limit_choices_to={'agent_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guestbook_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='guestbook_ended_at',
            field=models.DateTimeField(blank=True, help_text="Fin de la mission : le livre d'or se referme, videz ce champ pour la rouvrir.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guestbook_started_at',
            field=models.DateTimeField(blank=True, help_text="Debut de la mission de l'agent, horodate automatiquement au premier demarrage.", null=True),
        ),
    ]
