# Generated by Django 5.2.16 on 2026-09-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_guestbook_agent_event_guestbook_ended_at_and_more'),
        ('processing', '0008_musictrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_music_track',
            field=models.ForeignKey(blank=True, help_text="Piste choisie a la main pour le film de cet evenement (par l'equipe Memora, ou l'organisateur si on le lui ouvre un jour). Remplace le choix automatique par ambiance, qui ne peut plus vraiment varier depuis que l'invite ne choisit plus de moment.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_events', to='processing.musictrack'),
        ),
    ]
