# Generated by Django 5.2.16 on 2026-09-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_selected_music_track'),
        # Doit courir apres la copie des affectations existantes vers
        # GuestBookAssignment : sinon ces champs sont supprimes en premier.
        ('guestbook', '0006_migrate_existing_guestbook_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guestbook_agent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guestbook_ended_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='guestbook_started_at',
        ),
    ]
