# Generated by Django 5.2.16 on 2026-09-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_reprice_event_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='guestbook_agents_included',
            field=models.PositiveSmallIntegerField(default=0, help_text="Nombre d'agents Memora inclus, pour l'affichage (ex. 1 pour Grand jour, plus pour Prestige). Sans effet si « inclut le livre d'or » est decoche."),
        ),
        migrations.AddField(
            model_name='eventplan',
            name='includes_guestbook',
            field=models.BooleanField(default=False, help_text="Cette formule inclut le livre d'or video (agent(s) Memora a l'entree). Affichage uniquement : l'assignation reelle d'un agent reste manuelle en admin, sans blocage technique lie a la formule."),
        ),
        migrations.AddField(
            model_name='eventplan',
            name='requires_quote',
            field=models.BooleanField(default=False, help_text="Prix sur devis : masque le prix (affiche « Sur devis ») et retire cette formule du formulaire de creation en libre-service. A creer/attacher manuellement depuis l'admin apres discussion du tarif avec le client."),
        ),
    ]
