# Generated by Django 5.2.16 on 2026-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_reshape_event_plan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, help_text="Date d'envoi du recu de paiement a l'organisateur. Vide = pas encore envoye.", null=True),
        ),
    ]
