# Generated by Django 5.2.16 on 2026-09-13 13:41

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_receipt_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_music_bpm',
            field=models.FloatField(blank=True, help_text="Tempo mesure automatiquement a l'upload. Sert au calage des coupes.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_music_file',
            field=models.FileField(blank=True, help_text="Musique fournie par l'organisateur lui-meme : prioritaire sur tout choix automatique ou manuel. L'organisateur est seul responsable des droits sur ce fichier (voir CGU, section Contenus).", null=True, upload_to=events.models.event_custom_music_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_music_first_beat_offset',
            field=models.FloatField(default=0.0, help_text='Decalage du premier temps fort, en secondes.'),
        ),
    ]
