# Generated by Django 5.2.16 on 2026-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_custom_music_bpm_event_custom_music_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_preview_enabled',
            field=models.BooleanField(default=False, help_text="Réservé aux essais de l'équipe : ouvre la collecte aux invités avant le jour de l'événement (par défaut, le lien affiche « Rendez-vous le … » jusqu'à la date). À retirer une fois le test terminé.", verbose_name='ouvert aux invités avant la date (test)'),
        ),
    ]
