# Generated by Django 5.2.16 on 2026-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_guest_preview_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deliverable_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Rappel envoye a l'organisateur avant la suppression definitive de son film. Vide = pas encore envoye.", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='retention_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text="Rappel envoye a l'organisateur avant le retrait de ses souvenirs bruts. Vide = pas encore envoye.", null=True),
        ),
    ]
