# Generated by Django 5.2.16 on 2026-09-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_retention_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_opening_time',
            field=models.TimeField(blank=True, help_text="Heure (le jour de l'événement) à partir de laquelle les invités peuvent prendre des photos et vidéos avec le QR code. Vide = dès minuit.", null=True, verbose_name="heure d'ouverture du QR code"),
        ),
    ]
