# Generated by Django 5.2.16 on 2026-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_guest_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remote_guestbook_enabled',
            field=models.BooleanField(default=False, help_text="Ouvre la page « proches absents » (memoracd.site/e/<slug>/proches/), protegee par des codes a usage unique que l'organisateur genere lui-meme et transmet un par un.", verbose_name="livre d'or ouvert aux proches absents"),
        ),
    ]
