# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_remote_guestbook_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text="Marque manuellement par l'equipe Memora une fois l'evenement clos : l'organisateur ne peut alors plus modifier les informations de l'evenement (voir EventUpdateView). Vide = toujours modifiable.", null=True),
        ),
    ]
