# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_finalized_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInterestClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_clicks', to='events.eventplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
