# Generated by Django 5.0.14 on 2026-07-17 16:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def create_default_site_configuration(apps, schema_editor):
    SiteConfiguration = apps.get_model('core', 'SiteConfiguration')
    SiteConfiguration.objects.get_or_create(
        pk=1,
        defaults={
            'event_price_amount': settings.MEMORA_EVENT_PRICE_AMOUNT,
            'event_price_currency': settings.MEMORA_EVENT_PRICE_CURRENCY,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_price_amount', models.PositiveIntegerField(default=5900, help_text='Montant en centimes. Exemple : 5900 pour 59 USD.', validators=[django.core.validators.MinValueValidator(1)])),
                ('event_price_currency', models.CharField(default='USD', help_text='Code devise ISO sur 3 lettres, par exemple USD ou EUR.', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration Memora',
                'verbose_name_plural': 'configuration Memora',
            },
        ),
        migrations.RunPython(create_default_site_configuration, migrations.RunPython.noop),
    ]
