# Generated by Django 5.0.14 on 2026-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_medium_amount',
            field=models.PositiveIntegerField(default=1000, help_text='Commission en centimes par événement payé pour le palier Medium. Exemple : 1000 pour 10 USD.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_premium_amount',
            field=models.PositiveIntegerField(default=2000, help_text='Commission en centimes par événement payé pour le palier Premium. Exemple : 2000 pour 20 USD.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_referral_amount',
            field=models.PositiveIntegerField(default=500, help_text="Commission en centimes versée au parrain pour chaque événement payé d'un filleul. 0 pour désactiver."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_starter_amount',
            field=models.PositiveIntegerField(default=500, help_text='Commission en centimes par événement payé pour le palier Starter. Exemple : 500 pour 5 USD.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tier_medium_min_events',
            field=models.PositiveIntegerField(default=51, help_text="Nombre d'événements payés à partir duquel l'organisateur passe Medium. Exemple : 51."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tier_premium_min_events',
            field=models.PositiveIntegerField(default=101, help_text="Nombre d'événements payés à partir duquel l'organisateur passe Premium. Exemple : 101."),
        ),
    ]
