# Generated by Django 5.0.14 on 2026-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_commission_medium_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='cgu_effective_date',
            field=models.DateField(blank=True, help_text="Date d'entrée en vigueur des CGU. Vide = date du jour à l'affichage.", null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_name',
            field=models.CharField(default='Memora', help_text='Nom commercial du produit, affiché partout (marque, pages légales).', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hosting_provider',
            field=models.CharField(blank=True, default='', help_text='Hébergeur du service, mentionné dans les mentions légales (ex. Render, OVH).', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_address',
            field=models.CharField(blank=True, default='', help_text='Adresse postale ou siège social affiché sur les pages légales.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_contact_email',
            field=models.EmailField(blank=True, default='', help_text='Adresse e-mail de contact affichée sur les pages légales.', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_country',
            field=models.CharField(blank=True, default='', help_text='Pays / juridiction dont relèvent les CGU (ex. France, Belgique).', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_entity_name',
            field=models.CharField(blank=True, default='', help_text='Raison sociale de la société qui édite le service. Laisser vide pour reprendre le nom commercial.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_effective_date',
            field=models.DateField(blank=True, help_text="Date d'entrée en vigueur de la politique de confidentialité. Vide = date du jour à l'affichage.", null=True),
        ),
    ]
