# Generated by Django 5.0.14 on 2026-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_cgu_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='data_protection_authority',
            field=models.CharField(blank=True, default='', help_text='Autorité de contrôle compétente (ex. la CNIL en France).', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_publication_director',
            field=models.CharField(blank=True, default='', help_text='Directeur de la publication (mentions légales).', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_registration_number',
            field=models.CharField(blank=True, default='', help_text="Numéro d'immatriculation de la société (ex. RCS Paris 000 000 000).", max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='legal_share_capital',
            field=models.CharField(blank=True, default='', help_text='Capital social, mention légale facultative (ex. 10 000 €).', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_provider_name',
            field=models.CharField(blank=True, default='', help_text='Prestataire de paiement (ex. Stripe). Utilisé dans les CGU et la confidentialité.', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='refund_window_days',
            field=models.PositiveIntegerField(default=14, help_text='Délai de rétractation / remboursement en jours, à adapter selon votre politique.'),
        ),
    ]
