# Generated by Django 5.2.16 on 2026-07-27 10:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_data_protection_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_medium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text="Commission en % du prix de l'événement pour le palier Medium.", max_digits=5),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_mode',
            field=models.CharField(choices=[('percent', 'Pourcentage du prix'), ('fixed', 'Montant fixe')], default='percent', help_text="Mode de calcul des commissions. « Pourcentage » s'adapte automatiquement aux formules (un événement à 199 rapporte plus qu'un à 49).", max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_premium_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text="Commission en % du prix de l'événement pour le palier Premium.", max_digits=5),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_referral_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Commission en % versée au parrain pour chaque événement payé d'un filleul. 0 pour désactiver.", max_digits=5),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='commission_starter_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Commission en % du prix de l'événement pour le palier Starter. Exemple : 10 pour 10 %.", max_digits=5),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='upload_quota_grace_percent',
            field=models.PositiveSmallIntegerField(default=10, help_text='Marge de tolérance en % au-delà du quota de souvenirs de la formule, avant blocage réel. Évite de bloquer des invités en pleine fête. Exemple : 10.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='commission_starter_amount',
            field=models.PositiveIntegerField(default=500, help_text='Commission en centimes par événement payé pour le palier Starter. Exemple : 500 pour 5 USD. Utilisé uniquement en mode « Montant fixe ».'),
        ),
    ]
