# Generated by Django 5.2.16 on 2026-07-27 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_commission_medium_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='first_event_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text="Remise en % accordée sur le PREMIER événement d'un organisateur venu avec le code d'un ambassadeur. 0 pour désactiver la remise.", max_digits=5),
        ),
    ]
