# Generated by Django 5.2.16 on 2026-07-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_first_event_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='minimum_payout_amount',
            field=models.PositiveIntegerField(default=2000, help_text='Montant minimum en centimes pour demander un retrait. Exemple : 2000 pour 20 USD.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='referral_duration_days',
            field=models.PositiveIntegerField(default=365, help_text="Durée d'une affiliation, en jours. Passé ce délai le filleul n'est plus rattaché à son parrain, qui cesse de toucher des commissions sur lui. 0 = affiliation à vie."),
        ),
    ]
