# Generated by Django 5.2.16 on 2026-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_minimum_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='support_email',
            field=models.EmailField(blank=True, default='', help_text="Adresse de contact affichée aux organisateurs qui ont perdu leur mot de passe. Laisser vide pour reprendre l'adresse de contact légale.", max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='support_whatsapp',
            field=models.CharField(blank=True, default='', help_text='Numéro WhatsApp au format international, par exemple +243990000000. Laisser vide pour ne pas proposer WhatsApp.', max_length=30),
        ),
    ]
