# Generated by Django 5.2.16 on 2026-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfiguration_support_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "etat d'exploitation",
                'verbose_name_plural': "etats d'exploitation",
            },
        ),
    ]
