# Generated by Django 5.0.14 on 2026-07-08 20:31

import django.db.models.deletion
import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echec')], default='pending', max_length=24)),
                ('final_file', models.FileField(blank=True, null=True, upload_to=processing.models.generated_movie_upload_path)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('error_logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_movies', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='processing__event_i_bc4559_idx'), models.Index(fields=['created_at'], name='processing__created_b8ecda_idx')],
            },
        ),
    ]
