# Generated by Django 5.0.14 on 2026-07-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
        ('uploads', '0006_guestupload_auto_approved_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echec')], default='pending', max_length=24)),
                ('provider', models.CharField(default='local_heuristic_v1', max_length=80)),
                ('technical_score', models.FloatField(default=0)),
                ('emotion_score', models.FloatField(default=0)),
                ('energy_score', models.FloatField(default=0)),
                ('movie_score', models.FloatField(default=0)),
                ('brightness', models.FloatField(blank=True, null=True)),
                ('sharpness', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('error_logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='uploads.guestupload')),
            ],
            options={
                'verbose_name': 'analyse media',
                'verbose_name_plural': 'analyses medias',
                'ordering': ['-movie_score', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='processing__status_a969f5_idx'), models.Index(fields=['movie_score'], name='processing__movie_s_6e2d6c_idx')],
            },
        ),
    ]
