# Generated by Django 5.0.14 on 2026-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_mediaanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='edit_decision_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='music_mood',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='music_track',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='render_provider',
            field=models.CharField(default='ffmpeg', max_length=40),
        ),
        migrations.AddField(
            model_name='mediaanalysis',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
