# Generated by Django 5.0.14 on 2026-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_generatedmovie_edit_decision_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='progress_message',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
