# Generated by Django 5.0.14 on 2026-07-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_generatedmovie_progress_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='organizer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
