# Generated by Django 5.0.14 on 2026-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_generatedmovie_organizer_notified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmovie',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=24),
        ),
        migrations.AlterField(
            model_name='mediaanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=24),
        ),
    ]
