# Generated by Django 5.0.14 on 2026-07-22 00:18

import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_alter_generatedmovie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='full_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='full_file',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.generated_movie_upload_path),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='teaser_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedmovie',
            name='teaser_file',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.generated_movie_upload_path),
        ),
    ]
