# Generated by Django 5.2.16 on 2026-07-24 10:37

import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0007_generatedmovie_full_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('audio_file', models.FileField(upload_to=processing.models.music_track_upload_path)),
                ('mood', models.CharField(choices=[('romantic_cinematic', 'Romantique / cinematique'), ('cinematic_emotional', 'Emotion / recueillement'), ('joyful_party', 'Joyeux / fete'), ('warm_lounge', 'Chaleureux / lounge'), ('elegant_warm', 'Elegant / neutre')], default='elegant_warm', max_length=32)),
                ('bpm', models.FloatField(blank=True, help_text="Tempo mesure automatiquement a l'upload. Sert au calage des coupes.", null=True)),
                ('first_beat_offset', models.FloatField(default=0.0, help_text='Decalage du premier temps fort, en secondes.')),
                ('is_active', models.BooleanField(default=True, help_text='Seules les pistes actives sont utilisees dans les films.')),
                ('attribution', models.CharField(blank=True, default='', help_text="Credit a afficher si la licence l'exige (ex. CC-BY).", max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='Provenance et licence, pour vos archives (ex. Pixabay, YouTube Audio Library).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'piste musicale',
                'verbose_name_plural': 'bibliotheque musicale',
                'ordering': ['mood', 'title'],
            },
        ),
    ]
