# Generated by Django 5.2.16 on 2026-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_generatedmovie_media_purged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmovie',
            name='progress_percent',
            field=models.FloatField(default=0, help_text="Avancement 0-100, a la decimale pres pendant le rendu Remotion (voir processing.remotion.render_movie_with_remotion) : un chiffre qui bouge vraiment rassure plus qu'un entier fige plusieurs minutes."),
        ),
    ]
