# Generated by Django 5.2.16 on 2026-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_alter_generatedmovie_progress_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='is_guestbook_default',
            field=models.BooleanField(default=False, help_text="Fond sonore utilise pour TOUS les montages du livre d'or (sauf si l'organisateur a fourni sa propre musique ou choisi une piste precise pour son evenement). Une seule piste active devrait porter cette case ; en cas de plusieurs, la plus ancienne gagne.", verbose_name="piste par defaut du livre d'or"),
        ),
    ]
