# Generated by Django 5.2.16 on 2026-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_musictrack_guestbook_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
