# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_generatedmovie_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
