# Generated by Django 5.2.16

import processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_generatedmovie_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmovie',
            name='teaser_light_file',
            field=models.FileField(blank=True, null=True, upload_to=processing.models.generated_movie_upload_path),
        ),
    ]
