# Generated by Django 5.2.16 on 2026-08-31 14:05

import django.db.models.deletion
import guestbook.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0013_event_guestbook_agent_event_guestbook_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='Facultatif : de la part de qui est ce message.', max_length=120)),
                ('media_file', models.FileField(upload_to=guestbook.models.guestbook_message_upload_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_messages', to='events.event')),
                ('recorded_by', models.ForeignKey(help_text='Agent qui a capture ce message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_guestbook_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "message du livre d'or",
                'verbose_name_plural': "messages du livre d'or",
                'ordering': ['-created_at'],
            },
        ),
    ]
