# Generated by Django 5.2.16 on 2026-09-10 09:13

import django.db.models.deletion
import guestbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_selected_music_track'),
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('final_file', models.FileField(blank=True, null=True, upload_to=guestbook.models.guestbook_movie_upload_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('render_provider', models.CharField(default='remotion', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('trigger', models.CharField(blank=True, max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_movie', to='events.event')),
            ],
            options={
                'verbose_name': "montage du livre d'or",
                'verbose_name_plural': "montages du livre d'or",
                'ordering': ['-updated_at'],
            },
        ),
    ]
