# Generated by Django 5.2.16 on 2026-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_guestbookmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmessage',
            name='media_purged',
            field=models.BooleanField(default=False),
        ),
    ]
