# Generated by Django 5.2.16 on 2026-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_guestbookmessage_media_purged'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmovie',
            name='media_purged',
            field=models.BooleanField(default=False),
        ),
    ]
