# Generated by Django 5.2.16 on 2026-09-11 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depend on the pre-removal state of Event : the data migration that
        # follows (0006) still needs guestbook_agent/started_at/ended_at to
        # exist before events.0015 drops them.
        ('events', '0014_event_selected_music_track'),
        ('guestbook', '0004_guestbookmovie_media_purged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, help_text='Debut du service de cet agent, horodate automatiquement au premier demarrage.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fin du service de cet agent. Videz ce champ pour le rouvrir.', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(help_text="Agent Memora affecte au livre d'or video de cet evenement.", limit_choices_to={'agent_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_assignments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbook_assignments', to='events.event')),
            ],
            options={
                'verbose_name': "mission agent livre d'or",
                'verbose_name_plural': "missions agent livre d'or",
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'agent'), name='unique_guestbook_assignment')],
            },
        ),
    ]
