# Generated by Django 5.2.16 on 2026-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0006_migrate_existing_guestbook_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmovie',
            name='progress_message',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='guestbookmovie',
            name='progress_percent',
            field=models.FloatField(default=0, help_text='Avancement 0-100, a la decimale pres pendant le rendu Remotion (voir processing.guestbook_montage.render_guestbook_montage).'),
        ),
    ]
