# Generated by Django 5.2.16 on 2026-09-20 10:03

import guestbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0007_guestbookmovie_progress_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookmovie',
            name='final_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestbookmovie',
            name='light_file',
            field=models.FileField(blank=True, null=True, upload_to=guestbook.models.guestbook_movie_upload_path),
        ),
        migrations.AddField(
            model_name='guestbookmovie',
            name='light_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestbookmovie',
            name='progress_percent',
            field=models.FloatField(default=0, help_text='Avancement 0-100, a la decimale pres pendant le montage (voir processing.guestbook_montage.render_guestbook_montage).'),
        ),
        migrations.AlterField(
            model_name='guestbookmovie',
            name='render_provider',
            field=models.CharField(default='remotion+ffmpeg', max_length=40),
        ),
    ]
