# Generated by Django 5.2.16 on 2026-09-26 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_remote_guestbook_enabled'),
        ('guestbook', '0008_guestbookmovie_light_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteGuestbookCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text="Marque manuelle : l'organisateur a deja transmis ce code a quelqu'un.", null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_name', models.CharField(blank=True, help_text="Prenom saisi par le proche au moment de l'envoi de son message.", max_length=120)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_guestbook_codes', to='events.event')),
            ],
            options={
                'verbose_name': "code livre d'or a distance",
                'verbose_name_plural': "codes livre d'or a distance",
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'code'), name='unique_remote_guestbook_code')],
            },
        ),
    ]
