# Generated by Django 5.0.14 on 2026-07-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_accent_event_type_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('own', 'Événement propre'), ('referral', 'Événement filleul')], max_length=12)),
                ('tier', models.CharField(blank=True, default='', help_text='Palier appliqué au moment du gain (commissions sur événement propre).', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Montant en centimes, figé au moment du gain.')),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='events.event')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('medium', 'Medium'), ('premium', 'Premium')], default='starter', help_text="Palier calculé automatiquement d'après le nombre d'événements payés.", max_length=20)),
                ('referral_code', models.CharField(max_length=12, unique=True)),
                ('tier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text="Organisateur dont le code de parrainage a été utilisé à l'inscription.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil organisateur',
                'verbose_name_plural': 'profils organisateurs',
            },
        ),
        migrations.AddConstraint(
            model_name='commissionledger',
            constraint=models.UniqueConstraint(fields=('event', 'kind'), name='unique_commission_per_event_kind'),
        ),
    ]
