# Generated by Django 5.0.14 on 2026-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles_and_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='became_ambassador_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='is_ambassador',
            field=models.BooleanField(default=False, help_text='Statut accordé manuellement par Memora. Seuls les ambassadeurs perçoivent des commissions ; les autres sont des organisateurs simples.'),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('medium', 'Medium'), ('premium', 'Premium')], default='starter', help_text="Palier calculé automatiquement d'après le nombre d'événements payés (ambassadeurs).", max_length=20),
        ),
    ]
