# Generated by Django 5.2.16 on 2026-07-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organizerprofile_became_ambassador_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='first_event_discount_used_at',
            field=models.DateTimeField(blank=True, help_text="Date a laquelle la remise de bienvenue a ete consommee (premier evenement paye avec le code d'un ambassadeur). Vider pour la redonner.", null=True),
        ),
    ]
