# Generated by Django 5.2.16 on 2026-07-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizerprofile_first_event_discount_used_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='referred_at',
            field=models.DateTimeField(blank=True, help_text="Début de l'affiliation. Elle expire après la durée réglée dans la configuration Memora ; le parrain cesse alors de toucher des commissions.", null=True),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant demande en centimes, fige a la demande.')),
                ('currency', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Virement bancaire'), ('other', 'Autre')], default='mobile_money', max_length=20)),
                ('payout_details', models.CharField(help_text='Numero Mobile Money, IBAN ou coordonnees de versement.', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('rejected', 'Refusée')], default='pending', max_length=12)),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de retrait',
                'verbose_name_plural': 'demandes de retrait',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='commissionledger',
            name='payout_request',
            field=models.ForeignKey(blank=True, help_text='Demande de retrait qui porte cette commission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='accounts.payoutrequest'),
        ),
    ]
