# Generated by Django 5.2.16 on 2026-09-13 09:24

import accounts.models
import accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_agentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text="Date d'acceptation des CGU a l'inscription. Preuve de consentement, ne pas modifier.", null=True),
        ),
        migrations.CreateModel(
            name='AmbassadorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document_number', models.CharField(help_text="Numéro de la pièce d'identité (carte d'identité, passeport...).", max_length=60)),
                ('id_document_file', models.FileField(help_text="Photo scannée ou photographiée de la pièce d'identité.", storage=accounts.storage.identity_document_storage, upload_to=accounts.models.identity_document_upload_path)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=12)),
                ('tamper_risk_score', models.PositiveSmallIntegerField(default=0, help_text="Indice heuristique 0-100 (métadonnées + analyse de recompression). N'est pas une preuve de fraude : sert à prioriser l'examen humain.")),
                ('tamper_flags', models.JSONField(blank=True, default=list, help_text='Anomalies détectées automatiquement à la soumission, pour information.')),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidature ambassadeur',
                'verbose_name_plural': 'candidatures ambassadeur',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
