# Generated by Django 5.0.14 on 2026-07-08 20:31

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "categorie d'upload",
                'verbose_name_plural': "categories d'upload",
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GuestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to=uploads.models.guest_media_upload_path)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=12)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('is_selected_for_movie', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_uploads', to='events.event')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_uploads', to='uploads.uploadcategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['event', 'uploaded_at'], name='uploads_gue_event_i_8dba95_idx'), models.Index(fields=['event', 'media_type'], name='uploads_gue_event_i_fc6892_idx'), models.Index(fields=['event', 'is_deleted'], name='uploads_gue_event_i_0cda16_idx'), models.Index(fields=['ip_address', 'uploaded_at'], name='uploads_gue_ip_addr_772210_idx'), models.Index(fields=['session_key', 'uploaded_at'], name='uploads_gue_session_06ef9c_idx')],
            },
        ),
    ]
