# Generated by Django 5.0.14 on 2026-07-16 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


FALLBACK_UPLOAD_CATEGORIES = [
    ("ceremony", "Ceremonie", 1),
    ("arrival", "Arrivee", 2),
    ("cocktail", "Cocktail", 3),
    ("reception", "Reception", 4),
    ("speech", "Discours", 5),
    ("dancefloor", "Piste de danse", 6),
    ("cake", "Gateau", 7),
    ("funny", "Moment drole", 8),
    ("emotional", "Moment emouvant", 9),
    ("other", "Autre", 10),
]

AUTO_PROMOTION_USAGE_THRESHOLD = 3


def normalize_moment_label(value):
    normalized = " ".join((value or "").strip().split())[:80]
    if normalized.islower() or normalized.isupper():
        return normalized.capitalize()
    return normalized


def upsert_moment_template(MomentTemplate, code, label, status, is_active=True, usage_count=0, event_type=None):
    normalized_label = normalize_moment_label(label)
    if not normalized_label:
        return None

    normalized_code = code or slugify(normalized_label)[:40] or "moment"
    moment, created = MomentTemplate.objects.update_or_create(
        code=normalized_code,
        defaults={
            "label": normalized_label,
            "status": status,
            "is_active": is_active,
            "usage_count": usage_count,
        },
    )
    if event_type:
        moment.suggested_event_types.add(event_type)
    return moment


def seed_moment_templates(apps, schema_editor):
    UploadCategory = apps.get_model("uploads", "UploadCategory")
    UploadCategoryTemplate = apps.get_model("uploads", "UploadCategoryTemplate")
    MomentTemplate = apps.get_model("uploads", "MomentTemplate")

    for template in UploadCategoryTemplate.objects.select_related("event_type"):
        code = template.code or slugify(normalize_moment_label(template.label))[:40] or "moment"
        usage_count = UploadCategory.objects.filter(code=code).count()
        upsert_moment_template(
            MomentTemplate,
            code=code,
            label=template.label,
            status="approved",
            is_active=template.is_active,
            usage_count=usage_count,
            event_type=template.event_type,
        )

    for code, label, _sort_order in FALLBACK_UPLOAD_CATEGORIES:
        usage_count = UploadCategory.objects.filter(code=code).count()
        upsert_moment_template(
            MomentTemplate,
            code=code,
            label=label,
            status="approved",
            usage_count=usage_count,
        )

    known_codes = set(MomentTemplate.objects.values_list("code", flat=True))
    for category in UploadCategory.objects.select_related("event__event_type").order_by("sort_order", "label"):
        if category.code in known_codes:
            continue
        usage_count = UploadCategory.objects.filter(code=category.code).count()
        status = "approved" if usage_count >= AUTO_PROMOTION_USAGE_THRESHOLD else "pending"
        moment = upsert_moment_template(
            MomentTemplate,
            code=category.code,
            label=category.label,
            status=status,
            is_active=category.is_active,
            usage_count=usage_count,
            event_type=category.event.event_type if category.event_id else None,
        )
        if moment:
            known_codes.add(moment.code)


def remove_seeded_moment_templates(apps, schema_editor):
    MomentTemplate = apps.get_model("uploads", "MomentTemplate")
    MomentTemplate.objects.filter(created_by__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_paid_at_event_payment_provider_and_more'),
        ('uploads', '0006_guestupload_auto_approved_by_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'A valider'), ('approved', 'Valide'), ('rejected', 'Rejete')], default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('auto_promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_moment_templates', to=settings.AUTH_USER_MODEL)),
                ('suggested_event_types', models.ManyToManyField(blank=True, related_name='moment_templates', to='events.eventtype')),
            ],
            options={
                'verbose_name': 'moment global',
                'verbose_name_plural': 'moments globaux',
                'ordering': ['label'],
            },
        ),
        migrations.RunPython(seed_moment_templates, remove_seeded_moment_templates),
    ]
