# Generated by Django 5.2.16 on 2026-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_selected_music_track'),
        ('uploads', '0008_accent_default_moment_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestupload',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestupload',
            name='media_purged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='guestupload',
            index=models.Index(fields=['is_deleted', 'deleted_at', 'media_purged'], name='uploads_gue_is_dele_851988_idx'),
        ),
    ]
