# Generated by Django 5.2.16 on 2026-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_guestupload_deleted_at_guestupload_media_purged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestupload',
            name='device_cookie',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guestupload',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guestupload',
            name='device_signature',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
