# Generated by Django 5.2.16 on 2026-09-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_guestupload_device_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestupload',
            name='is_selected_for_teaser',
            field=models.BooleanField(default=False),
        ),
    ]
